/* eslint-disable */
// AUTO-GENERATED by scripts/generate_openapi_types.py.
// Do not edit by hand; update Pydantic schemas and rerun `npm run generate:api-types`.

export type ApiErrorPayload = {
  code: string;
  message: string;
  details: Record<string, unknown>;
};

export type Page<T> = {
  items: T[];
  total: number;
  page: number;
  page_size: number;
  pages: number;
};

export type AlertLogSchema = {
  timestamp_utc: string | null;
  timestamp_bj: string | null;
  id: number;
  rule_name: string;
  message: string;
  channel: string;
  delivered: boolean;
};

export type AlertRuleSchema = {
  name: string;
  rule_type: string;
  params: Record<string, unknown>;
  channels: string[];
  cooldown_minutes: number;
  enabled: boolean;
};

export type AlertTestResponse = {
  ok: boolean;
  message: string;
};

export type AlertWebhookStatus = {
  configured: boolean;
  preview: string | null;
};

export type AnnotationCreateRequest = {
  symbol: string;
  window_start_utc: string;
  window_end_utc: string;
  threshold_pct: number;
  selected_news_ids?: number[];
  no_clear_news?: boolean;
  notes?: string | null;
  labeler?: string | null;
  candidate_news_ids?: number[] | null;
  auto_reasoning?: string | null;
  auto_summary?: string | null;
  news_roles?: Record<string, string> | null;
  market_reaction_type?: string | null;
  confidence?: number | null;
  auto_news_roles?: Record<string, string> | null;
  context_pre_minutes?: number | null;
};

export type AnnotationDetail = {
  id: number;
  symbol: string;
  asset_class: string | null;
  window_start: TimeFields;
  window_end: TimeFields;
  context_start: TimeFields;
  context_end: TimeFields;
  threshold_pct: number | null;
  price_start: number | null;
  price_end: number | null;
  change_pct: number | null;
  selected_news_ids: number[];
  selected_news: NewsItemSchema[];
  candidate_news_ids: number[];
  no_clear_news: boolean;
  notes: string | null;
  labeler: string | null;
  auto_reasoning: string | null;
  auto_summary: string | null;
  news_roles: Record<string, string>;
  market_reaction_type: string | null;
  confidence: number | null;
  auto_news_roles: Record<string, string>;
  prompt_version: string | null;
  eval_set: boolean;
  created_at: TimeFields;
  updated_at: TimeFields;
};

export type AnnotationListItem = {
  id: number;
  symbol: string;
  asset_class: string | null;
  window_start: TimeFields;
  window_end: TimeFields;
  change_pct: number | null;
  references: ReferenceChange[];
  no_clear_news: boolean;
  selected_count: number;
  market_reaction_type: string | null;
  confidence: number | null;
  eval_set: boolean;
  needs_review: boolean;
  labeler: string | null;
  notes: string | null;
  created_at: TimeFields;
  updated_at: TimeFields;
};

export type AnnotationResponse = {
  id: number;
  saved: boolean;
};

export type AnnotationSymbol = {
  symbol: string;
  name: string;
  asset_class: string;
};

export type AutoAnnotateBatchItem = {
  symbol: string;
  window_start_utc: string;
  window_end_utc: string;
  selected_news_ids: number[];
  no_clear_news: boolean;
  news_roles: Record<string, string>;
  market_reaction_type: string | null;
  confidence: number | null;
  summary: string;
  reasoning: string;
  candidate_count: number;
  candidate_news_ids: number[];
};

export type AutoAnnotateBatchRequest = {
  windows?: AutoAnnotateRequest[];
};

export type AutoAnnotateBatchResponse = {
  results: AutoAnnotateBatchItem[];
  reasoning: string;
  model: string;
  duration_seconds: number;
  requested_count: number;
  answered_count: number;
};

export type AutoAnnotateRefineRequest = {
  symbol: string;
  window_start_utc: string;
  window_end_utc: string;
  threshold_pct: number;
  context_pre_minutes: number | null;
  prior_news_roles: Record<string, string> | null;
  prior_summary: string | null;
  prior_confidence: number | null;
  user_message: string;
};

export type AutoAnnotateRequest = {
  symbol: string;
  window_start_utc: string;
  window_end_utc: string;
  threshold_pct: number;
  context_pre_minutes?: number | null;
};

export type AutoAnnotateResponse = {
  selected_news_ids: number[];
  no_clear_news: boolean;
  news_roles: Record<string, string>;
  market_reaction_type: string | null;
  confidence: number | null;
  summary: string;
  reasoning: string;
  model: string;
  duration_seconds: number;
  candidate_count: number;
};

export type BehaviorDailyResponse = {
  symbol: string;
  days: BehaviorDailySchema[];
};

export type BehaviorDailySchema = {
  utc_date: string;
  day_type: string;
  counts: Record<string, Record<string, number>>;
  composition: Record<string, number>;
  down_net_sum: number | null;
  computed_at: TimeFields;
  live: boolean;
};

export type BehaviorLinkageResponse = {
  symbol: string;
  hours: number;
  rolling_points: number;
  series: LinkageSeries[];
  breadth: BreadthPoint[];
};

export type BehaviorNewsBrief = {
  id: number;
  time: TimeFields;
  title: string;
  magnitude_tier: string | null;
  topic: string | null;
};

export type BehaviorSegmentSchema = {
  id: number;
  symbol: string;
  start: TimeFields;
  end: TimeFields;
  key_ts: TimeFields | null;
  direction: number;
  tier_idx: number;
  tier_max: number;
  net_pct: number;
  amp_pct: number | null;
  classification: string | null;
  class_version: string | null;
  s_scores: Record<string, SScoreSchema>;
  max_abs_s: number | null;
  news: BehaviorNewsBrief[];
};

export type BehaviorSegmentsResponse = {
  symbol: string;
  days: number;
  segments: BehaviorSegmentSchema[];
};

export type BreadthPoint = {
  t: TimeFields;
  count: number | null;
};

export type ContextNewsResponse = {
  items: NewsItemSchema[];
};

export type DeleteAnnotationResponse = {
  id: number;
  deleted: boolean;
};

export type LinkagePoint = {
  t: TimeFields;
  s: number | null;
};

export type LinkageSeries = {
  symbol: string;
  label: string;
  points: LinkagePoint[];
};

export type MarketHistoryPoint = {
  timestamp_utc: string | null;
  timestamp_bj: string | null;
  symbol: string;
  name: string;
  price: number;
  normalized_pct: number | null;
  source: string | null;
};

export type MarketHistoryResponse = {
  symbols: string[];
  start: TimeFields;
  end: TimeFields;
  series: MarketHistorySeries[];
};

export type MarketHistorySeries = {
  symbol: string;
  name: string;
  asset_class: string | null;
  points: MarketHistoryPoint[];
};

export type MarketLatestItem = {
  timestamp_utc: string | null;
  timestamp_bj: string | null;
  name: string;
  symbol: string;
  asset_class: string;
  source: string;
  price: number;
  prev_price: number | null;
  change_pct: number | null;
  change_5m: number | null;
  change_1h: number | null;
  change_24h: number | null;
};

export type MarketLatestResponse = {
  items: MarketLatestItem[];
  last_updated: TimeFields | null;
};

export type MarketSymbol = {
  symbol: string;
  name: string;
  asset_class: string;
};

export type MarketTableRow = {
  timestamp_utc: string | null;
  timestamp_bj: string | null;
  asset_class: string;
  name: string;
  symbol: string;
  price: number;
  prev_price: number | null;
  change_pct: number | null;
  volume: number | null;
  source: string;
};

export type NewsItemSchema = {
  timestamp_utc: string | null;
  timestamp_bj: string | null;
  id: number;
  source: string;
  source_id: string | null;
  title: string;
  content: string | null;
  url: string | null;
  source_importance: number | null;
  llm_importance: number | null;
  llm_importance_reason: string | null;
  llm_model: string | null;
  language: string;
  categories: string | null;
  is_jin10_important: boolean;
  topic: string | null;
  magnitude_tier: string | null;
  news_direction: string | null;
};

export type NewsResponse = {
  items: NewsItemSchema[];
  total: number;
  page: number;
  page_size: number;
  zh_count: number;
  en_count: number;
};

export type NewsSourceMeta = {
  key: string;
  name: string;
  language: string;
};

export type NewsTagUpdateRequest = {
  topic: string | null;
  magnitude_tier: string | null;
  news_direction: string | null;
};

export type PredictionFamily = {
  id: string;
  name: string;
  series: PredictionFamilySeries[];
};

export type PredictionFamilySeries = {
  market_id: string;
  question: string;
  label: string;
  order: number;
  points: PredictionRow[];
};

export type PredictionMarketSummary = {
  market_id: string;
  question: string;
  volume: number | null;
  outcomes: PredictionRow[];
  has_shift: boolean;
};

export type PredictionRow = {
  timestamp_utc: string | null;
  timestamp_bj: string | null;
  market_id: string;
  question: string;
  outcome: string;
  probability: number;
  prev_probability: number | null;
  probability_pct: number;
  delta_pct: number | null;
  volume: number | null;
};

export type PredictionsResponse = {
  markets: PredictionMarketSummary[];
  latest_timestamp: TimeFields | null;
};

export type PriceRuleSchema = {
  symbol: string;
  threshold_pct: number;
  window_minutes: number;
};

export type PriceWindowSchema = {
  symbol: string;
  asset_class: string;
  name: string;
  window_start: TimeFields;
  window_end: TimeFields;
  configured_window_minutes: number;
  actual_window_minutes: number;
  price_start: number;
  price_end: number;
  change_pct: number;
  segment_count: number;
  annotation_id: number | null;
  annotatable: boolean;
  is_primary: boolean;
  context_pre_minutes: number;
  references: ReferenceChange[];
};

export type ReferenceChange = {
  symbol: string;
  label: string;
  pre_pct: number | null;
  pct: number | null;
  post_pct: number | null;
  correlation: number | null;
  unit: string;
  is_self: boolean;
};

export type SScoreSchema = {
  s: number;
  ess: number;
  coverage: number;
};

export type SectorLeaderboardResponse = {
  snapshot_at: TimeFields | null;
  rows: SectorLeaderboardRow[];
};

export type SectorLeaderboardRow = {
  category: string;
  group: string | null;
  token_count: number;
  ret_1h: number | null;
  ret_24h: number | null;
  ret_168h: number | null;
  ret_720h: number | null;
  ret_1h_median: number | null;
  ret_24h_median: number | null;
  ret_168h_median: number | null;
  ret_720h_median: number | null;
};

export type SectorTokenRow = {
  symbol: string;
  binance_symbol: string;
  market: string;
  ret_1h: number | null;
  ret_24h: number | null;
  ret_168h: number | null;
  ret_720h: number | null;
};

export type SectorTokensResponse = {
  category: string;
  group: string | null;
  snapshot_at: TimeFields | null;
  tokens: SectorTokenRow[];
};

export type TaskStatus = {
  task_id: string;
  status: string;
  created_at: TimeFields;
  started_at: TimeFields | null;
  finished_at: TimeFields | null;
  message: string | null;
  result: Record<string, unknown> | null;
  error: string | null;
};

export type TimeFields = {
  timestamp_utc: string | null;
  timestamp_bj: string | null;
};

export type TrackedMarketCreate = {
  kind: "slug";
  identifier: string;
  display_name?: string | null;
  notes?: string | null;
};

export type TrackedMarketSchema = {
  id: number;
  kind: "slug";
  identifier: string;
  display_name: string | null;
  enabled: boolean;
  notes: string | null;
};

export type TrackedMarketUpdate = {
  enabled?: boolean | null;
  display_name?: string | null;
  notes?: string | null;
};

export type AlertLog = AlertLogSchema;
export type AlertRule = AlertRuleSchema;
export type NewsItem = NewsItemSchema;
export type PriceRule = PriceRuleSchema;
export type PriceWindow = PriceWindowSchema;
export type TrackedMarket = TrackedMarketSchema;
export type TrackedMarketCreatePayload = TrackedMarketCreate;
export type TrackedMarketUpdatePayload = TrackedMarketUpdate;
