"""Generate frontend TypeScript API types from FastAPI OpenAPI schemas."""
from __future__ import annotations

from pathlib import Path
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from api.app import create_app

OUT = ROOT / "frontend" / "src" / "api" / "types.ts"

SKIP_COMPONENTS = {
    "HTTPValidationError",
    "ValidationError",
    "Page_AlertLogSchema_",
    "Page_AnnotationListItem_",
    "Page_MarketTableRow_",
}

COMPAT_ALIASES = {
    "AlertLog": "AlertLogSchema",
    "AlertRule": "AlertRuleSchema",
    "NewsItem": "NewsItemSchema",
    "PriceRule": "PriceRuleSchema",
    "PriceWindow": "PriceWindowSchema",
    "TrackedMarket": "TrackedMarketSchema",
    "TrackedMarketCreatePayload": "TrackedMarketCreate",
    "TrackedMarketUpdatePayload": "TrackedMarketUpdate",
}

REQUEST_COMPONENTS = {
    "AnnotationCreateRequest",
    "AutoAnnotateBatchRequest",
    "AutoAnnotateRequest",
    "TrackedMarketCreate",
    "TrackedMarketUpdate",
}


def main() -> None:
    openapi = create_app(enable_scheduler=False).openapi()
    schemas: dict[str, dict[str, Any]] = openapi.get("components", {}).get("schemas", {})
    lines = [
        "/* eslint-disable */",
        "// AUTO-GENERATED by scripts/generate_openapi_types.py.",
        "// Do not edit by hand; update Pydantic schemas and rerun `npm run generate:api-types`.",
        "",
        "export type ApiErrorPayload = {",
        "  code: string;",
        "  message: string;",
        "  details: Record<string, unknown>;",
        "};",
        "",
        "export type Page<T> = {",
        "  items: T[];",
        "  total: number;",
        "  page: number;",
        "  page_size: number;",
        "  pages: number;",
        "};",
        "",
    ]

    for name in sorted(schemas):
        if name in SKIP_COMPONENTS:
            continue
        lines.extend(_emit_schema(name, schemas[name]))
        lines.append("")

    for alias, target in COMPAT_ALIASES.items():
        lines.append(f"export type {alias} = {target};")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")


def _emit_schema(name: str, schema: dict[str, Any]) -> list[str]:
    force_required = name not in REQUEST_COMPONENTS
    return [f"export type {name} = {_schema_to_ts(schema, force_required=force_required)};"]


def _schema_to_ts(schema: dict[str, Any], *, force_required: bool = False) -> str:
    if "$ref" in schema:
        return _ref_name(schema["$ref"])

    if "const" in schema:
        return _literal(schema["const"])

    if "enum" in schema:
        return " | ".join(_literal(value) for value in schema["enum"]) or "unknown"

    if "allOf" in schema:
        return " & ".join(_schema_to_ts(part, force_required=force_required) for part in schema["allOf"])

    if "anyOf" in schema or "oneOf" in schema:
        parts = schema.get("anyOf") or schema.get("oneOf") or []
        return _dedupe_union(_schema_to_ts(part, force_required=force_required) for part in parts)

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return _dedupe_union(
            _schema_to_ts({**schema, "type": item}, force_required=force_required)
            for item in schema_type
        )

    if schema_type == "null":
        return "null"
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        return f"{_schema_to_ts(schema.get('items', {}), force_required=force_required)}[]"
    if schema_type == "object" or "properties" in schema:
        return _object_to_ts(schema, force_required=force_required)

    return "unknown"


def _object_to_ts(schema: dict[str, Any], *, force_required: bool = False) -> str:
    properties: dict[str, dict[str, Any]] = schema.get("properties", {})
    additional = schema.get("additionalProperties")
    required = set(schema.get("required", []))

    if not properties:
        if isinstance(additional, dict):
            return f"Record<string, {_schema_to_ts(additional, force_required=force_required)}>"
        return "Record<string, unknown>"

    rows = ["{"]
    for prop, prop_schema in properties.items():
        optional = "" if force_required or prop in required else "?"
        rows.append(
            f"  {_prop_name(prop)}{optional}: "
            f"{_schema_to_ts(prop_schema, force_required=force_required)};"
        )
    if isinstance(additional, dict):
        rows.append(
            f"  [key: string]: {_schema_to_ts(additional, force_required=force_required)};"
        )
    rows.append("}")
    return "\n".join(rows)


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return repr(str(value)).replace("'", '"')


def _dedupe_union(parts: Any) -> str:
    seen: list[str] = []
    for part in parts:
        if part not in seen:
            seen.append(part)
    return " | ".join(seen) or "unknown"


def _prop_name(name: str) -> str:
    return name if name.replace("_", "").isalnum() and not name[0].isdigit() else _literal(name)


if __name__ == "__main__":
    main()
